### ISSUE TITLE
Barco DCS-200 telnet connection

### ISSUE THREAD

**Issue by Stillerm** [bitfocus/companion-module-dcs#2]
Hello

i have various dcs200 from Barco and i cannot connect to them from companion, it seems to be a problem connecting through port 23 on telnet as it requests a login with username and password, though in a newer firmware release barco introduced telnet via port 3000 without authentication.

i have tried connecting using the template o barco pds from companion, in pds the port 3000 is implemented as factory preset and it works fine, i can control the dcs, but some keys and commands are different, the pds has a pip whereas the dcs has a luminance key and the i can‘t activate that as the commands are different. Any chance of changing the connection to dcs?

I can go on activating the key manually or with a telnet session, but it would be nice to have it on a button.

thanks

**Comment by JeffreyDavidsz** [comment]
Saw this one coming in, changed it. Please test

**Comment by Stillerm** [comment]
Hello jeffrey

Unfortunately i tried but it still didn’t work
Using the same machine in “PDS Emulation” it does it all or almost, connecting from that same hardware to the same machine as Real DCS-200 it doesn’t find it, neither on port 23 nor on port 3000, stays yellow, initializing

thanks

Michael Stiller


Da: Jeffrey Davidsz <notifications@github.com>
Risposta: bitfocus/companion-module-barco-dcs <reply@reply.github.com>
Data: mercoledì 3 marzo 2021 17:29
A: bitfocus/companion-module-barco-dcs <companion-module-barco-dcs@noreply.github.com>
Cc: Stillerm <Stiller_m@msn.com>, Author <author@noreply.github.com>
Oggetto: Re: [bitfocus/companion-module-barco-dcs] Barco DCS-200 telnet connection (#2)


Saw this one coming in, changed it. Please test
